version: '3'
services:
    laravel_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        networks:
            - laravel

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        environment:
            SA_PASSWORD: "YourStrong!Passw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
