version: '3'
services:
    laravel_app:
        build: .
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"  # Cambia el mapeo de puerto a 80
        networks:
            - laravel

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        environment:
            SA_PASSWORD: "P@ssw0rd2024!"  # Contraseña SA
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - laravel
        volumes:
            - ./sqlserver/init-scripts:/docker-entrypoint-initdb.d/

networks:
    laravel:
        driver: bridge
