version: '3'
services:
    laravel_app:
        image: php:8.0-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        networks:
            - laravel

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: sqlserver
        environment:
            SA_PASSWORD: "control123"  # Aquí asignas la contraseña al usuario SA
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - laravel
        volumes:
            - ./sqlserver/init-scripts:/docker-entrypoint-initdb.d/  # Para los scripts de inicialización

networks:
    laravel:
        driver: bridge
